# Generated by Django 4.2.1 on 2023-07-05 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='ctext',
        ),
    ]
